version: '3.9'

services:
  api:
    build:
      context: .
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    environment:
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
      - FLASK_APP=osemu
    command: sh -c "flask run"
    stop_signal: SIGINT

  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass

volumes:
  dev-db-data: