version: '3.9'

services:
  api:
    build:
      context: .
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    environment:
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
      - FLASK_APP=osemu
      - FLASK_DEV_SECRET_KEY=devkey
      - APP_DB=osemudata
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    command: flask run
    stop_signal: SIGINT
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  dev-db-data: