version: '3.9'
name: osemu_test

services:
  api:
    build:
      context: .
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    environment:
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
      - FLASK_APP=osemu
      - FLASK_SECRET_KEY=devkey
      - APP_DB=test_osemudata
      - POSTGRES_DEFAULT_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db_test
      - POSTGRES_PORT=5433
      - USING_TEST_DB=
      - ADMIN_USER_EMAIL=admin@example.com
      - ADMIN_USER_PASSWORD=123123
    command: sh -c "python manage.py wait-for-db && 
                    python manage.py create-db &&
                    python manage.py upgrade-db &&
                    python manage.py test"
    stop_signal: SIGINT
    depends_on:
      - db_test
    networks:
      - testnet

  db_test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 5433
    expose:
      - "5433"
    networks:
      - testnet
  
networks:
  testnet:
    driver: bridge