"""empty message

Revision ID: c8c74f5391ae
Revises: 
Create Date: 2023-02-24 19:14:28.949377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c74f5391ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('language',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('license',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('console',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('wiki_url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('emulator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('git_url', sa.String(length=512), nullable=True),
    sa.Column('gh_stars', sa.Integer(), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('latest_update', sa.DateTime(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('emu_console',
    sa.Column('emulator_id', sa.UUID(), nullable=True),
    sa.Column('console_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['console_id'], ['console.id'], ),
    sa.ForeignKeyConstraint(['emulator_id'], ['emulator.id'], )
    )
    op.create_table('emulator_language',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('emulator_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['emulator_id'], ['emulator.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('emulator_id', 'language_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emulator_language')
    op.drop_table('emu_console')
    op.drop_table('emulator')
    op.drop_table('console')
    op.drop_table('license')
    op.drop_table('language')
    op.drop_table('company')
    # ### end Alembic commands ###
